"""User-level autostart registration for the gateway service."""

from __future__ import annotations

from dataclasses import dataclass
import os
import plistlib
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

from ai_companion.paths import get_app_home


SERVICE_NAME = "ai-companion-gateway"
LAUNCHD_LABEL = "com.ai-companion.gateway"


@dataclass
class AutostartResult:
    """Result of registering the gateway for login/startup."""

    ok: bool
    method: str
    path: Path | None
    message: str


def register_gateway_autostart(
    *,
    python_executable: str | None = None,
    app_home: Path | None = None,
    platform: str | None = None,
    activate: bool = True,
) -> AutostartResult:
    """Register the gateway to start automatically when the user logs in."""

    platform_name = platform or sys.platform
    python = str(Path(python_executable or sys.executable).resolve())
    home = Path(app_home) if app_home is not None else get_app_home()
    (home / "logs").mkdir(parents=True, exist_ok=True)

    if platform_name == "win32":
        return _register_windows_startup(python, platform_name)
    if platform_name == "darwin":
        return _register_launch_agent(python, home)
    if platform_name.startswith("linux"):
        return _register_systemd_user_service(python, home, activate=activate)
    return AutostartResult(
        ok=False,
        method="unsupported",
        path=None,
        message=f"Unsupported platform for autostart: {platform_name}",
    )


def _gateway_command(python: str) -> list[str]:
    return [python, "-m", "ai_companion.gateway", "--daemon"]


def _register_windows_startup(python: str, platform_name: str) -> AutostartResult:
    startup_dir = _windows_startup_dir()
    if startup_dir is None:
        return AutostartResult(
            ok=False,
            method="windows-startup",
            path=None,
            message="APPDATA is not set; cannot locate the Windows Startup folder.",
        )

    startup_dir.mkdir(parents=True, exist_ok=True)
    script_path = startup_dir / f"{SERVICE_NAME}.vbs"
    command = " ".join(_windows_quote(arg) for arg in _gateway_command(python))
    script_path.write_text(
        "\n".join(
            [
                "' Generated by AI Companion. Starts the gateway at user login.",
                'Set shell = CreateObject("WScript.Shell")',
                f'shell.Run "{_vbs_string(command)}", 0, False',
                "",
            ]
        ),
        encoding="utf-8",
    )
    return AutostartResult(
        ok=True,
        method="windows-startup",
        path=script_path,
        message="Gateway autostart registered in the Windows Startup folder.",
    )


def _windows_startup_dir() -> Path | None:
    appdata = os.environ.get("APPDATA")
    if appdata:
        return Path(appdata) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"
    if sys.platform == "win32":
        return Path.home() / "AppData" / "Roaming" / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"
    return None


def _windows_quote(value: str) -> str:
    escaped = value.replace('"', r'\"')
    return f'"{escaped}"' if any(ch.isspace() for ch in value) else escaped


def _vbs_string(value: str) -> str:
    return value.replace('"', '""')


def _register_launch_agent(python: str, home: Path) -> AutostartResult:
    launch_agents_dir = Path.home() / "Library" / "LaunchAgents"
    launch_agents_dir.mkdir(parents=True, exist_ok=True)
    plist_path = launch_agents_dir / f"{LAUNCHD_LABEL}.plist"
    logs_dir = home / "logs"

    payload = {
        "Label": LAUNCHD_LABEL,
        "ProgramArguments": _gateway_command(python),
        "RunAtLoad": True,
        "KeepAlive": True,
        "WorkingDirectory": str(Path.home()),
        "StandardOutPath": str(logs_dir / "gateway.launchd.out.log"),
        "StandardErrorPath": str(logs_dir / "gateway.launchd.err.log"),
    }
    with plist_path.open("wb") as handle:
        plistlib.dump(payload, handle, sort_keys=False)

    return AutostartResult(
        ok=True,
        method="launchd",
        path=plist_path,
        message="Gateway autostart registered as a LaunchAgent.",
    )


def _register_systemd_user_service(python: str, home: Path, *, activate: bool) -> AutostartResult:
    systemd_dir = Path.home() / ".config" / "systemd" / "user"
    systemd_dir.mkdir(parents=True, exist_ok=True)
    service_path = systemd_dir / f"{SERVICE_NAME}.service"
    logs_dir = home / "logs"
    command = " ".join(shlex.quote(part) for part in _gateway_command(python))

    service_path.write_text(
        "\n".join(
            [
                "[Unit]",
                "Description=AI Companion Gateway",
                "After=network-online.target",
                "",
                "[Service]",
                "Type=simple",
                f"WorkingDirectory={Path.home()}",
                f"ExecStart=/bin/sh -lc {shlex.quote(command)}",
                "Restart=on-failure",
                "RestartSec=5",
                f"StandardOutput=append:{logs_dir / 'gateway.systemd.out.log'}",
                f"StandardError=append:{logs_dir / 'gateway.systemd.err.log'}",
                "",
                "[Install]",
                "WantedBy=default.target",
                "",
            ]
        ),
        encoding="utf-8",
    )

    if activate and shutil.which("systemctl"):
        for command_args in (
            ["systemctl", "--user", "daemon-reload"],
            ["systemctl", "--user", "enable", service_path.name],
        ):
            result = subprocess.run(command_args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
            if result.returncode != 0:
                return AutostartResult(
                    ok=True,
                    method="systemd-user",
                    path=service_path,
                    message=(
                        "Gateway systemd user service was written, but automatic enable failed. "
                        f"Run: systemctl --user enable {service_path.name}"
                    ),
                )

    return AutostartResult(
        ok=True,
        method="systemd-user",
        path=service_path,
        message="Gateway autostart registered as a systemd user service.",
    )


def main() -> int:
    result = register_gateway_autostart()
    prefix = "[OK]" if result.ok else "[WARN]"
    print(f"{prefix} {result.message}")
    if result.path:
        print(f"     {result.path}")
    return 0 if result.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
